import "@/styles/globals.css";
import ClientProviders from "../providers/ClientProviders";

export const metadata = {
    title: "WayniWallet",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html suppressHydrationWarning lang="en">
            <body>
                <ClientProviders>{children}</ClientProviders>
            </body>
        </html>
    );
}
